### ISSUE TITLE
panic/runtime error

### ISSUE THREAD

**Issue by campbell-lunar** [neodyme-labs/tailviz#3]
I get the following error when running the tool - any ideas on what's failing here?

```
user@device tailviz % go run main.go -i ~/Documents/GitHub/tailscale-acls/policy.hujson -o png
# github.com/goccy/go-graphviz/internal/ccall
In file included from common.c:5:
../../../go/pkg/mod/github.com/zaporter-work/go-graphviz@v0.0.0-20240206215244-40dc3408ad8a/internal/ccall/common/emit.c:165:35: warning: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Wsingle-bit-bitfield-constant-conversion]
../../../go/pkg/mod/github.com/zaporter-work/go-graphviz@v0.0.0-20240206215244-40dc3408ad8a/internal/ccall/common/emit.c:2540:24: warning: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Wsingle-bit-bitfield-constant-conversion]
../../../go/pkg/mod/github.com/zaporter-work/go-graphviz@v0.0.0-20240206215244-40dc3408ad8a/internal/ccall/common/emit.c:2596:35: warning: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Wsingle-bit-bitfield-constant-conversion]
../../../go/pkg/mod/github.com/zaporter-work/go-graphviz@v0.0.0-20240206215244-40dc3408ad8a/internal/ccall/common/emit.c:2602:35: warning: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Wsingle-bit-bitfield-constant-conversion]
../../../go/pkg/mod/github.com/zaporter-work/go-graphviz@v0.0.0-20240206215244-40dc3408ad8a/internal/ccall/common/emit.c:2612:31: warning: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Wsingle-bit-bitfield-constant-conversion]
../../../go/pkg/mod/github.com/zaporter-work/go-graphviz@v0.0.0-20240206215244-40dc3408ad8a/internal/ccall/common/emit.c:2623:31: warning: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Wsingle-bit-bitfield-constant-conversion]
../../../go/pkg/mod/github.com/zaporter-work/go-graphviz@v0.0.0-20240206215244-40dc3408ad8a/internal/ccall/common/emit.c:2628:31: warning: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Wsingle-bit-bitfield-constant-conversion]
../../../go/pkg/mod/github.com/zaporter-work/go-graphviz@v0.0.0-20240206215244-40dc3408ad8a/internal/ccall/common/emit.c:2641:28: warning: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Wsingle-bit-bitfield-constant-conversion]
../../../go/pkg/mod/github.com/zaporter-work/go-graphviz@v0.0.0-20240206215244-40dc3408ad8a/internal/ccall/common/emit.c:2650:33: warning: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Wsingle-bit-bitfield-constant-conversion]
../../../go/pkg/mod/github.com/zaporter-work/go-graphviz@v0.0.0-20240206215244-40dc3408ad8a/internal/ccall/common/emit.c:2659:32: warning: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Wsingle-bit-bitfield-constant-conversion]
../../../go/pkg/mod/github.com/zaporter-work/go-graphviz@v0.0.0-20240206215244-40dc3408ad8a/internal/ccall/common/emit.c:2668:32: warning: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Wsingle-bit-bitfield-constant-conversion]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104e66f90]

goroutine 1 [running]:
github.com/goccy/go-graphviz/cgraph.(*Graph).CreateEdge(0x1051ba820?, {0x0?, 0x140000b54b0?}, 0xe?, 0x10519e4a0?)
	/Users/user/go/pkg/mod/github.com/zaporter-work/go-graphviz@v0.0.0-20240206215244-40dc3408ad8a/cgraph/cgraph.go:963 +0x20
main.main.func1(0x14000096540)
	/Users/user/Documents/GitHub/tailviz/main.go:214 +0xc7c
github.com/urfave/cli/v2.(*Command).Run(0x14000148160, 0x14000096540, {0x1400009a050, 0x5, 0x5})
	/Users/user/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:279 +0x71c
github.com/urfave/cli/v2.(*App).RunContext(0x14000146000, {0x10521b348, 0x10553e120}, {0x1400009a050, 0x5, 0x5})
	/Users/user/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:337 +0x514
github.com/urfave/cli/v2.(*App).Run(...)
	/Users/user/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:311
main.main()
	/Users/user/Documents/GitHub/tailviz/main.go:263 +0x490
exit status 2
```

**Comment by kilimnik** [comment]
Yeah, it was a mistake in the code. It should be fixed now. 

I also noticed, that you specified the output wrong. It is supposed to be a path not only the type

**Comment by campbell-lunar** [comment]
Ah, fantastic - thanks.  And yes, I see now that issue with my output path!
